apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: LoadBalancer
  ports:
    - name: "http"
      port: 80
      targetPort: 8082
  selector:
    io.kompose.service: backend
  loadBalancerIP: 35.226.121.153